# Generated by Django 4.2.20 on 2025-04-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalized_guest_experience', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending Payment', 'Pending Payment'), ('Cancelled', 'Cancelled')], default='Pending Payment', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
