# Generated by Django 4.2.20 on 2025-04-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalized_guest_experience', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('tags', models.CharField(max_length=255)),
            ],
        ),
    ]
