# Generated by Django 4.2.20 on 2025-04-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalized_guest_experience', '0004_liveevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liveevent',
            old_name='title',
            new_name='location',
        ),
        migrations.AddField(
            model_name='liveevent',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
