# Generated by Django 4.2.20 on 2025-04-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalized_guest_experience', '0005_rename_title_liveevent_location_liveevent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveevent',
            name='location',
        ),
        migrations.AddField(
            model_name='liveevent',
            name='locations',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='liveevent',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='liveevent',
            name='tags',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='liveevent',
            name='venue',
            field=models.CharField(max_length=200),
        ),
    ]
