# Generated by Django 4.2.20 on 2025-04-27 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalized_guest_experience', '0007_surpriseactivity_rename_locations_liveevent_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalized_guest_experience.room'),
        ),
    ]
