# Generated by Django 4.2.20 on 2025-04-27 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personalized_guest_experience', '0010_remove_activity_description_remove_activity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200)),
                ('activity_description', models.TextField()),
                ('activity_location', models.CharField(max_length=200)),
                ('activity_time', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('planned_activities', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.RemoveField(
            model_name='chatbotinteraction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tripplan',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='ChatbotInteraction',
        ),
        migrations.DeleteModel(
            name='TripPlan',
        ),
        migrations.AddField(
            model_name='triprecommendation',
            name='user_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='personalized_guest_experience.usertrip'),
        ),
    ]
