# Generated by Django 4.1.3 on 2023-01-01 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("parking_zones", "0008_auto_20210214_1237"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="park",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
