# Generated by Django 4.1.3 on 2023-01-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_rooms_room_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rooms",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("1", "Premium suite"),
                    ("2", "Deluxe suite"),
                    ("3", "Presidential suite"),
                ],
                max_length=50,
            ),
        ),
    ]
