# Generated by Django 4.1.4 on 2022-12-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_category_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularpizza',
            name='category_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sicilianpizza',
            name='category_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='order',
            field=models.TextField(blank=True, null=True),
        ),
    ]
