# Generated by Django 4.1.3 on 2023-01-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_alter_regularpizza_category_description_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pasta",
            new_name="PakistaniCusine",
        ),
        migrations.DeleteModel(
            name="RegularPizza",
        ),
        migrations.DeleteModel(
            name="SicilianPizza",
        ),
        migrations.DeleteModel(
            name="Toppings",
        ),
        migrations.AlterField(
            model_name="category",
            name="category_description",
            field=models.TextField(default="Enjoy the meal!!", max_length=400),
        ),
        migrations.AlterField(
            model_name="userorder",
            name="order",
            field=models.TextField(default=None),
        ),
    ]
