# Generated by Django 4.1.3 on 2023-01-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_rename_pasta_pakistanicusine_delete_regularpizza_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MexicanCuisine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dish_name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name="PakistaniCuisine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dish_name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name="TurkishCuisine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dish_name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RenameModel(
            old_name="PakistaniCusine",
            new_name="FrenchCuisine",
        ),
        migrations.RenameModel(
            old_name="Salad",
            new_name="ItalianCuisine",
        ),
        migrations.DeleteModel(
            name="DinnerPlatters",
        ),
        migrations.DeleteModel(
            name="Sub",
        ),
    ]
