# Generated by Django 4.1.3 on 2023-01-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_rename_frenchcuisine_pakistancuisine"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PakistaniCuisine",
        ),
    ]
