# Generated by Django 4.1.3 on 2023-01-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_delete_pakistanicuisine"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PakistanCuisine",
            new_name="PakistaniCuisine",
        ),
    ]
