# Generated by Django 4.1.3 on 2023-01-02 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0017_frenchcuisine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userorder",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
